### ISSUE TITLE
RS007 Use a JFileChooser for select the main class

### ISSUE THREAD

**Issue by javierobledo** [JSwingRipples2016/jswingripples#13]

**Comment by jacquems** [comment]
- Description: Allow selection of the main class using JFileChooser, and thus, starting the analysis from it. 
- Source: Analyst
- Priority: Desirable
- Stability: Tradeable
- Actualization date: 01-11-2016
- State: Fulfils
- Increment: 1
- Type: Interation
- Associated user: End-User

User requirements associated:  
- [RU003: Main class selected automatically](https://github.com/JSwingRipples2016/jswingripples/wiki/User-Requirements#ru003-main-class-selected-automatically)

Software Change Process:
- [x] Initiation 
- [x] Concept Location  
- [x] Impact Analysis 
- [x] Prefactoring 
- [x] Actualization
- [x] Postfactoring
- [x] Conclusion

**Comment by Sircrab** [comment]
This enhancement is already implemented, closing this issue.

**Comment by jacquems** [comment]
**Initiation:**
Use a JFileChooser for select the main class by a selected project.

**Comment by jacquems** [comment]
**Concept Location:**
main class, project

**Comment by jacquems** [comment]
**Impact Analysis:**
StartAnalysisAction

**Comment by jacquems** [comment]
**Prefactoring:**
Here, the button "ok" was declared in the scope of the constructor in the class StartAnalysisDialog. However, this button must be enabled/disabled by another methods when a java file is selected or typed. For these reasons, this button is declared like global variable.

**Comment by jacquems** [comment]
**Actualization:**
First, a new global string variable is needed with the path of the selected project, declared with the name "project". Thus, is created a new button that allow to choose a Java file starting by the source folder of the project. The name of this file is displayed in the jText className.
Pull Request [#40]

**Comment by jacquems** [comment]
**Postfactoring:**
- The first comment was related to the project variable, which should be type JavaProject and not only its path. It was modified. 
- Some comment was deleted of the code. 
[commit #7407e60](https://github.com/JSwingRipples2016/jswingripples/commit/7407e60ae99ad24be2240be9c316919007962203)

**Comment by jacquems** [comment]
**Conclusion:**
A new functionality was implemented. Now, the user can be select the Java file through JFileChooser.
