### ISSUE TITLE
The search bar should be disabled when there has been no analysis performed

### ISSUE THREAD

**Issue by jacquems** [JSwingRipples2016/jswingripples#21]
Currently an exception is thrown

**Comment by sgioia9** [comment]
@Sircrab 
I think this was fixed here 
https://github.com/JSwingRipples2016/jswingripples/pull/11

**Comment by Sircrab** [comment]
@jacquems 
I just downloaded a clean copy of the master branch on another computer and this feature has already been implemented as @sgioia9 mentioned on the pull request #11 

Check that you're using the last version of the branch. I'll close this issue for now.
