### ISSUE TITLE
RS003 "Impact Analysis" should work

### ISSUE THREAD

**Issue by javierobledo** [JSwingRipples2016/jswingripples#32]
Description: Fix the Impact Analysis analysis. When a user select de java main class, this should be marked at the beginning and it should allow make propagation and add other marks.

Source: Team / Teacher
Priority: High
Stability: Non-Negotiable
Last Update: 2016-11-01
State: Pull Request
Increment: 1 
Type: Interation 
Associated user: End-User

User requirements associated:
* [RU001: All options should work (not only Change Propagation)](https://github.com/JSwingRipples2016/jswingripples/wiki/User-Requirements#ru001-all-options-should-work-not-only-change-propagation)

Software Change Process:
- [X] Concept Location
- [X] Impact Analysis 
- [ ] Prefactoring 
- [ ] Actualization
- [ ] Postfactoring
- [ ] Conclusion

**Comment by sgioia9** [comment]
@emilio-aburto taking this
