### ISSUE TITLE
RS034: Connect a jripples project with a GitHub repository

### ISSUE THREAD

**Issue by cfierro94** [JSwingRipples2016/jswingripples#47]
- Description: Provide a way to associate a project to a GitHub repository. This option should be available in projects settings. Also if a project is cloned from GH, its repository should be setted automatically.
- Source: Team/Teacher
- Priority: High
- Stability: Non-negotiable
- Update date: 30/11/2016
- State: Complies
- Increment: 2
- Type: Functional
- Associated user: End-users

User requirements associated:

- [RU011](https://github.com/JSwingRipples2016/jswingripples/wiki/User-Requirements#ru011-github-integration)

Software Change Process:

- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Actualization
- [x] Postfactoring
- [ ] Conclusion

Solved:
Add gif here

**Comment by sgioia9** [comment]
https://github.com/JSwingRipples2016/jswingripples/pull/59

**Comment by cfierro94** [comment]
I think this library does not do what we want to, I searched how to clone a project and I just found this (http://stackoverflow.com/questions/30892451/java-github-api-org-kohsuke-github-clone-repository-to-local-machine)

**Comment by jestebanlh** [comment]
This requirement have ben changed. The tasks for the issue are:

-Create a new tab in settings for GitHub Connection: Inside this tab you should type the url of the repository and make the connection.
-The connection should be validated.
-When the connection is established the issues of the repository are saved in file in csv format (If you have other ideas about it, please post them)
-Save the connection parameter in the XML file where the project parameter is keeped
