### ISSUE TITLE
RS029: GUI: add issues visualization

### ISSUE THREAD

**Issue by cfierro94** [JSwingRipples2016/jswingripples#49]
Description: Add a GUI capable of showing Github issues. 

An idea for opening this GUI could be to right click a project and select and option named "Show Github issues", this option should open a new tab in the main view area similar to the ones when doing an analysis. 

Source: Teacher
Priority: High
Stability: Negotiable
Last Update: 2016-11-15
State: Doesn't fullfill. 
Increment: 2
Type: Operational
Associated user: End-User

User requirements associated:
* [RU011: Github Integration](https://github.com/JSwingRipples2016/jswingripples/wiki/User-Requirements#ru011-github-integration)

Software Change Process:
- [X] Concept Location
- [X] Impact Analysis 
- [X] Prefactoring 
- [X] Actualization
- [X] Postfactoring
- [X] Conclusion

MockUp:
[jswingripples-github-GUI.pdf](https://github.com/JSwingRipples2016/jswingripples/files/610125/jswingripples-github-GUI.pdf)

**Comment by amorenocb** [comment]
Teacher asked us to come up with a prototype of a GUI before implementing it.

**Comment by javierobledo** [comment]
## Initialization
Add a GUI capable of showing Github issues

**Comment by javierobledo** [comment]
## Concept Location
**Significant concepts:** GUI
**Concept to be implemented:** Github, Issue
**Communication:** Add

**Comment by javierobledo** [comment]
## Impact Analysis

**Comment by javierobledo** [comment]
##Prefactoring, Actualization, Postfactoring
Nothing happend because the code isn't changed. Only a Mockup for the GUI was designed

**Comment by javierobledo** [comment]
## Conclusion
A mockup with the visual representation fo the Github requirements was showed to the teacher and the classmates during the presentation of iteration 2. The mockup was approved.
