### ISSUE TITLE
RS032 The main selection should be automatic

### ISSUE THREAD

**Issue by javierobledo** [JSwingRipples2016/jswingripples#54]

**Comment by jacquems** [comment]
- Description: The system should automatically display the main class when choosing a project to analyze. 
![image](https://cloud.githubusercontent.com/assets/22397517/20457581/1c1089a0-ae6d-11e6-96e9-852afabfda7b.png)

- Source: Team
- Priority: Desirable
- Stability: Tradable
- Actualization date: 19-11-2016
- State: Fulfils
- Increment: 0
- Type: Interation
- Associated user: End-User

User requirements associated:  
- [RU003: Main class selected automatically](https://github.com/JSwingRipples2016/jswingripples/wiki/User-Requirements#ru003-main-class-selected-automatically)

Software Change Process:
- [x] Initiation 
- [x] Concept Location  
- [ ] Impact Analysis 
- [ ] Prefactoring 
- [ ] Actualization
- [ ] Postfactoring
- [ ] Conclusion

**Comment by jacquems** [comment]
Initiation:
Automatically show the main class when choosing a project to analyze.

**Comment by jacquems** [comment]
**Concept Location:**
Main, Project, Analysis

**Comment by jacquems** [comment]
**Impact Analysis:**

**Comment by jacquems** [comment]
**Prefactoring:**

**Comment by jacquems** [comment]
**Actualization:**
MainClassSearchDialog.java

**Comment by jacquems** [comment]
**Post-factoring:**

**Comment by jacquems** [comment]
**Conclusion:**
The functionality of search the main class was improved, allowing select the java files with a main class in a new dialog window.
