### ISSUE TITLE
RS034 Modify the "x" for closing tabs for close with right clic

### ISSUE THREAD

**Issue by javierobledo** [JSwingRipples2016/jswingripples#56]
Description: Make all JTabbedPanes implement the close tab option with right click.

Source: Developers
Priority: Medium
Stability: Negotiable
Last Update: 2016-11-16
State: Doesn't fullfill. 
Increment: 1 
Type: Operational
Associated user: End-User

User requirements associated:
* [RU009: User interface enhancement](https://github.com/JSwingRipples2016/jswingripples/wiki/User-Requirements#ru009-user-interface-enhancement)

Software Change Process:
- [x] Concept Location
- [x] Impact Analysis 
- [x] Prefactoring 
- [x] Actualization
- [x] Postfactoring
- [x] Conclusion

**Comment by sgioia9** [comment]
@amorenocb
