### ISSUE TITLE
RS035 Disable "Go" and "Clear" buttons after all tabs are closed

### ISSUE THREAD

**Issue by javierobledo** [JSwingRipples2016/jswingripples#57]
Description: After close all tabs, the search buttons should be disabled
![rs035](https://cloud.githubusercontent.com/assets/8240682/20462964/f83c48e8-af07-11e6-9d20-910f943de7d5.gif)
Source: Team / Teacher
Priority: Medium
Stability: Negotiable
Last Update: 2016-11-20
State: Solved
Increment: 2
Type: Interation
Associated user: End-User

User requirements associated:

- [x] Initiation 
- [x] Concept Location  
- [x] Impact Analysis 
- [x] Prefactoring 
- [x] Actualization
- [x] Postfactoring
- [x] Conclusion

Solved:
![rs035fix](https://cloud.githubusercontent.com/assets/8240682/20468213/12694bba-af73-11e6-8c8e-ed6ab452cd11.gif)

**Comment by sgioia9** [comment]
@Sircrab

**Comment by javierobledo** [comment]
**Initiation:**
Disable "Go" and "Clear" buttons on the search menu after all tabs are closed

**Comment by javierobledo** [comment]
**Concept Location:**
JSwingRipplesApplication, Searcher, SearchMenu

**Comment by javierobledo** [comment]
## Impact Analysis
**Impacted classes:** ClearSearchAction, StartSearchWorker

**Comment by javierobledo** [comment]
## Prefactoring
Add a counter called tabbedAreaCount for count the tabs opened. When this counter is zero, the "Go" and "Clear" buttons are disabled.
Pull request

**Comment by javierobledo** [comment]
## Actualization
No clases were added to solve this issues

**Comment by javierobledo** [comment]
## Postfactoring
Change +=1 by ++ and -=1 by --

**Comment by javierobledo** [comment]
## Conclusion
![rs035fix](https://cloud.githubusercontent.com/assets/8240682/20468213/12694bba-af73-11e6-8c8e-ed6ab452cd11.gif)
