### ISSUE TITLE
RS009 Add a way to mark analysis' items

### ISSUE THREAD

**Issue by sgioia9** [JSwingRipples2016/jswingripples#6]
![bug2](https://cloud.githubusercontent.com/assets/6628178/19357210/0881a15a-9147-11e6-9f73-196e48325d4d.jpg)
Maybe by clicking on the empty "Mark" rectangle?

**Comment by javierobledo** [comment]
The marks are working. When you use a type of analysis by default, need to specify the main class in the "class name" text field. In this field, you need add the main class with the package. Example: If the project has the main class, called "DynamicScope", in the "dynamicscope" package, you need to write "dynamicscope.DynamicScope" in the class name field.
