### ISSUE TITLE
RS038: Create JTable with the list of issues

### ISSUE THREAD

**Issue by javierobledo** [JSwingRipples2016/jswingripples#71]
Description: Clic on the menu option "Show Issues" displays a TableView with the issues previously downloaded from GitHub
Source: Team / Teacher
Priority: High
Stability: Not Negotiable
Last Update: 2016-12-10
State: In progress
Increment: 3
Type: Interation
Associated user: End-User

User requirements associated:

- [x] Initiation 
- [x] Concept Location  
- [x] Impact Analysis 
- [x] Prefactoring 
- [ ] Actualization
- [ ] Postfactoring
- [ ] Conclusion

**Comment by jestebanlh** [comment]
I have been created the branch that have only the visual contextual buttom for it (Branch name: issue71) , because I created this buttom while I have been worked in the issue #72

**Comment by javierobledo** [comment]
## Initiation

Create JTable with the list of issues loaded from GitHub

**Comment by javierobledo** [comment]
## Concept Location

**Significant concepts:** Issues, GitHub
**Concept to be implemented:** JTable
**Communication:** Create
Issues concept located in ModelSerializer
GitHub concept located in ProjectSettingsEditor,MainMenuBar,JavaProject,GitSettings,GitHubSettings,JSwingRipplesApplication

**Comment by javierobledo** [comment]
##Impact Analysis
From ProjectSettingsEditor: SourceEditor
From JSwingRipplesApplication: ImportSource,DefaultController,GitSettings,ModelSaver,ProgressMonitorImpl,ProjectsView,ProjectViewMouseEvent,ProjectViewMouseListener,StartAnalysis,TaskProgressMonitor
From MainMenuBar: SearchBar,ShowCurrentStateAction,GraphVisualizationAction
From JavaProject: Statistics,ProjectsTreeCellRender,NewProjectWizard,ModuleConfiguration,ModelSerializerTest,ModelSerializer,MemberHierarchySupportTest,JavaProjectsModel,JavaProjectsModelTest,GitHubRepo,EdgesCalculatorTest
From GitSettings and GitHubSettings no one new classes are impacted

**Comment by javierobledo** [comment]
## Prefactoring
Added 3 clases, IssuesView for the JTable, IssusModel for the table settings and IssuesReader for read the XML file and load data to the table automatically. Pull Request #85

**Comment by javierobledo** [comment]
## Actualization
The jswingripples application now has a new option in the project menu, called "Show Issues". When this option is selected, a new tab appears in the main view area that shows the list of issues as a table, with two columns: issue number and title.

**Comment by javierobledo** [comment]
## Postfactoring
Deleted all DS_store files (generated by Mac), deleted automatic comments added by netbeans and added exceptions for open the XML file (for file note found and other xml parser errors). A message pop ups when the file is not found.

**Comment by javierobledo** [comment]
## Conclusion
![issue71-solved](https://cloud.githubusercontent.com/assets/8240682/21230364/7ca58b3e-c2c3-11e6-93c8-b4cec8807c7f.gif)
