### ISSUE TITLE
Executing a search query before performing an analysis results in unhandled exception

### ISSUE THREAD

**Issue by sgioia9** [JSwingRipples2016/jswingripples#9]
<img width="1208" alt="screen shot 2016-10-15 at 9 14 05 pm" src="https://cloud.githubusercontent.com/assets/6628178/19414240/7e5255d8-931c-11e6-9276-62c59362e899.png">

**Comment by Sircrab** [comment]
The exception also happens whenever there is a search query and there are no elements to return, even if an analysis was performed (i.e: searching for a term that doesn't exist)
